#!/bin/bash

pdflatex -output-directory paper/ paper/evolutive_algorithms.tex > custom.log
printf "\n#########################################################################\n\n" >> custom.log
bibtex paper/evolutive_algorithms.aux >> custom.log
printf "\n#########################################################################\n\n" >> custom.log
pdflatex -output-directory paper/ paper/evolutive_algorithms.tex >> custom.log
printf "\n#########################################################################\n\n" >> custom.log
pdflatex -output-directory paper/ paper/evolutive_algorithms.tex >> custom.log
